kubernetes example
dagger/examples pull request #5
Opened 2021-06-02 02:04 UTC by aluzzardi

First pass at a Kubernetes example

2021-06-02 02:37 UTC, aluzzardi commented
/cc @TomChv

2021-06-02 15:08 UTC, shykes requested changes
1. I like that we have a guide to deploying to Kubernetes, this will be very useful.

2. I left specific comments on the example itself.

3. I worry that our examples are inconsistent: voteapp and helloapp are names of apps, not specific to a particular infrastructure provider or use case, and have no companion guide. This app, in contrast, is named after a use case, and includes a detailed guide. Both are valid, but to have both together in the same repo is weird.

I think it would make more sense to 1) rename this example app to “hellogo”, or some other name which is consistent with the rest of the repo; and 2) move the guide itself to the docs. Otherwise this starts to feel like an alternate docs site. Better to bite the bullet and add a kubernetes guide to the docs itself. NOTE: I’m OK with doing this in a follow-up PR, if it’s logistically simpler to merge first.

2021-06-02 15:08 UTC, shykes commented on kubernetes/README.md
> +
Instead of changing, we can simply add lines.

—-
To deploy to GKE, we’re going to add a few lines to our plan. You can do this in a new file (for example `gke.cue`), or modify an existing cue file.

```cue
package main

import "dagger.io/gcp/gke"

gkeConfig: gke.#KubeConfig @dagger(input)
kubeconfig: gkeConfig.kubeconfig
```

This creates a new input called `gkeConfig`, and uses it to automatically generate a value for the `kubeConfig` input.
—-

2021-06-02 15:08 UTC, shykes commented on kubernetes/README.md
> +
Same as for GKE. Instead of changing, we can simply add lines.

—-
To deploy to Amazon EKS, we’re going to add a few lines to our plan. You can do this in a new file (for example ecs.cue), or modify an existing cue file.

```
package main

import "dagger.io/aws/eks"

eksConfig: eks.#KubeConfig @dagger(input)
kubeconfig: eksConfig.kubeconfig
```

This creates a new input called eksConfig, and uses it to automatically generate a value for the kubeConfig input.
—-

2021-06-02 18:01 UTC, aluzzardi commented
> I worry that our examples are inconsistent: voteapp and helloapp are names of apps, not specific to a particular infrastructure provider or use case, and have no companion guide. This app, in contrast, is named after a use case, and includes a detailed guide. Both are valid, but to have both together in the same repo is weird.

Agree about the detailed guide -- this is more of a scratch pad to prepare content for the docs.

I was under the impression that short term goal would be to move `dagger/dagger/examples` to `dagger/examples`, as it's weird to have two different places for examples (what goes into one vs the other? do we test them with a different infrastructure?).

Everything in `dagger/dagger/examples` is named after infrastructure providers and/or use cases: `jamstack`, `kubernetes-app`, `kubernetes-aws`, `react`, `simple-s3` so we already have inconsistency that needs to be addressed.

I thought we could have a couple of "named apps" as generic tutorials (hello, vote) that showcase multi-provider examples, and then a long series of per stack/use-case examples. Otherwise we'll end up with a long list of not so meaningful names (e.g. `todoapp` would be the react+netlify example, next to `hellogo`, `voteapp`, `helloapp`) which I don't think make navigation/discovery easy. Plus, we might re-use the same app for multiple use cases, in different examples (e.g. "todoapp" might be used both in netlify and s3).

WDYT?

2021-06-02 18:15 UTC, aluzzardi commented on kubernetes/.dagger/env/default/plan/app.cue
> +	name: "test"
The idea behind creating a `#Deployment` re-usable definition is that a kubernetes app is commonly made of different services.  This one has `app.cue` and a `nginx.cue` as a starting point that show how to deploy already existing images (nginx) and how to build/push/deploy from source (app).

I think making the deployment name an input assumes the config contains only a single deployment which I don't believe is the common use case (that's why people use helm in the first place).

The namespace however is an input so you're free to deploy this app as many times as you want on the same cluster (defaults to the `default` namespace)

2021-06-02 18:16 UTC, aluzzardi commented on kubernetes/README.md
> +
👍

2021-06-02 18:16 UTC, aluzzardi commented on kubernetes/README.md
> +
👍

2021-06-03 01:21 UTC, aluzzardi commented on kubernetes/README.md
> +## Preparation: Installing a local Kubernetes cluster
Unfortunately, it won't. You have to create the kubernetes cluster using that weird containerd patch inlined above (taken from the official kind documentation), otherwise the nodes won't be able to talk to your local registry.

2021-06-03 09:34 UTC, shykes commented on kubernetes/README.md
> +## Preparation: Installing a local Kubernetes cluster
Can’t that be solved by making the registry address an input, which would allow users to change it to their existing registry’s address?

2021-06-03 09:51 UTC, shykes commented
> I was under the impression that short term goal would be to move `dagger/dagger/examples` to `dagger/examples`, as it's weird to have two different places for examples (what goes into one vs the other? do we test them with a different infrastructure?).

Yes it’s weird to have 2 places for examples. But it’s not a good idea to combine them, because they are very different.

* The new examples are actual example apps: they show what using Dagger actually looks like in the context of a realistic project.

* The original examples are mini-guides with lots of example code, and very little text. They can be used as a starting point for adding guides to the docs.

My suggestion is to remove the original examples in the short term, to avoid confusion, and gradually re-incorporate some of their contents in the docs.

> Everything in `dagger/dagger/examples` is named after infrastructure providers and/or use cases: `jamstack`, `kubernetes-app`, `kubernetes-aws`, `react`, `simple-s3` so we already have inconsistency that needs to be addressed.

Correct, incorporating original examples (mini-guides, really) into the new examples repo would create inconsistency. Which is why we shouldn’t incorporate them.

> I thought we could have a couple of "named apps" as generic tutorials (hello, vote) that showcase multi-provider examples, and then a long series of per stack/use-case examples. Otherwise we'll end up with a long list of not so meaningful names (e.g. `todoapp` would be the react+netlify example, next to `hellogo`, `voteapp`, `helloapp`) which I don't think make navigation/discovery easy. Plus, we might re-use the same app for multiple use cases, in different examples (e.g. "todoapp" might be used both in netlify and s3).

So far we have 3 actual example apps:

* Helloapp (static web page that says hello)
* Voteapp (Docker’s voting app)
* Hellogo (Sam’s Go web application that says hello)

These examples don’t need to map 1-to-1 to use cases and guides. How they map exactly is TBD, suggestions are welcome. We can also adjust the number of apps: if 3 is too many, we can remove one. If it’s not enough, we can add more.

The important point is that example apps are not guides or use cases.

2021-06-03 21:44 UTC, aluzzardi commented
> These examples don’t need to map 1-to-1 to use cases and guides. How they map exactly is TBD, suggestions are welcome. We can also adjust the number of apps: if 3 is too many, we can remove one. If it’s not enough, we can add more.
> The important point is that example apps are not guides or use cases.

I see -- so you envision dagger/examples to contain just sample applications, not use case examples.

In that case, where do we stash specific examples of use cases?

Basically something like this:
https://github.com/pulumi/examples/tree/master/kubernetes-ts-nginx
Or this:
https://github.com/hashicorp/waypoint-examples/tree/main/gcp/google-cloud-run/nodejs

With this approach (it's a sample app not specific to a particular use case), it doesn't make sense for me to include the kubernetes plan in `examples/hellogo` at all -- that same app can be deployed on Kubernetes, ECS, Cloud Run, Lambda and others, why only include a Kubernetes plan. Unless the plan supports every single deployment platform dagger supports, but that's not a realistic example and makes it much harder to comprehend.

2021-06-04 13:34 UTC, shykes commented on kubernetes/.dagger/env/default/plan/app.cue
> +	name: "test"
Ok, I see. Makes sense.

2021-06-04 15:02 UTC, shykes commented
> I see -- so you envision dagger/examples to contain just sample applications, not use case examples.

I was picturing a hybrid: sample applications with pre-configured Dagger environments illustrating real-world uses of Dagger.

> In that case, where do we stash specific examples of use cases?
> 
> Basically something like this:
> https://github.com/pulumi/examples/tree/master/kubernetes-ts-nginx
> Or this:
> https://github.com/hashicorp/waypoint-examples/tree/main/gcp/google-cloud-run/nodejs

Good question, I agree it would be simplest if we could just follow the same pattern as Pulumi and Waypoint. But I think that we need a slightly different structure, because Dagger works differently. Specifically: 1) it’s very flexible, and 2) it’s embedded in an application (via gitflow). The combination of these two things make it harder to map tutorials to example apps 1-1.

* Waypoint is embedded in an application, but it’s not very flexible. There is only one use case for Waypoint: “deploy stateless application in language X to platform Y”. For each value of X and Y, there is a tutorial and a corresponding example app, which are useful standalone.

* Pulumi is very flexible, but it is not embedded in an application. Therefore, even though you can do many different things with Pulumi, it’s always in the context of a standalone Pulumi project. For example, “provision an S3 bucket and upload a file to it” makes sense as a standalone Pulumi example, because that’s how infrastructure engineers will use it. But it doesn’t make sense as a standalone Dagger example, because a realistic Dagger+S3 integration needs to take place in the context of an application (again, because of gitflow).

> With this approach (it's a sample app not specific to a particular use case), it doesn't make sense for me to include the kubernetes plan in `examples/hellogo` at all -- that same app can be deployed on Kubernetes, ECS, Cloud Run, Lambda and others, why only include a Kubernetes plan. Unless the plan supports every single deployment platform dagger supports, but that's not a realistic example and makes it much harder to comprehend.

What is missing is a system to map multiple tutorials to one example app. So each tutorial can show you how to add a cool feature to your example. Maybe each tutorial adds a new dagger environment; or each tutorial adds content to a base dagger environment; I’m not sure. But I think this would be a better fit.

I hope this helps clarify my thinking.

2021-07-07 10:45 UTC, closed without merging